#!/usr/bin/env python
import sys


sys.path.insert(0, '/opt/fremantleline/lib/python2.6/dist-packages')

def main():
    from fremantleline.ui import harmattan

if __name__ == "__main__":
    main()

